# ===== Framework Config (NO hardcoding in Java) =====
base.url=https://www.amazon.com/
signin.path=/ap/signin
browser=chrome
headless=false
window.size=1366x768

implicit.wait.seconds=0
explicit.wait.seconds=12
page.load.timeout.seconds=45

login.data.csv=src/test/resources/testdata/login_testdata.csv
results.csv=src/test/resources/results/login_results.csv

screenshots.base.dir=src/test/resources/results/screenshots
logs.base.dir=src/test/resources/results/logs

run.id.prefix=cold-breeze

use.homepage.signin=true
attempt.dismiss.overlays=true
